name: Generate Snake Contribution Graph

on:
  schedule:
    # Runs at midnight UTC every day
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  generate:
    name: Generate Snake Contribution Graph
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Generate the snake graph
      - name: Generate Snake Graph
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Step 3: Commit and push the generated graph
      - name: Commit and Push Snake Graph
        run: |
          mkdir -p dist
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add dist
          git commit -m "Update snake contribution graph" || echo "Nothing to commit"
          git push
